### ISSUE TITLE
Bump ws to 8.5 for custom WebSocket class

### ISSUE THREAD

**Issue by dsbudiac** [fastify/fastify-websocket#179]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

ws@8.5.0 allows for extending the WebSocket class.

### Motivation

Issue discussed here: https://github.com/websockets/ws/pull/2007

I forked myself and simply `npm i -P ws`, which seems to work fine. However I'm not sure how to navigate the [typescript def](https://github.com/fastify/fastify-websocket/blob/master/index.d.ts).

### Example

```ts
import fastify from 'fastify'
import websockets from 'fastify-websocket'
import WebSocket from 'ws'

class MyWebSocket extends WebSocket {
  foo() {
    return 'bar'
  }
}

const server = fastify()

server.register(websockets, {
  options: { WebSocket: MyWebSocket }
})
```

**Comment by dsbudiac** [comment]
Here's my fork: https://github.com/dsbudiac/fastify-websocket

**Comment by airhorns** [comment]
Not sure if the new option has been added to `@types/ws`, but that's what you'd need to bump in this repo's devDependencies as well to get that example code to typecheck. As you noticed, this package already does support passing down the options to the `ws` library, so I don't think any code or type changes should be needed here, just the dependency bumps. Want to create a PR?

**Comment by airhorns** [comment]
Ah I see -- I am not sure if what you want is going to be possible without the underlying type you linked being generic over that type, and even then I am not sure the way the types work with Fastify's plugin augmentation will let this work anyways. As a start, I think they'd need to do 

```
    interface ServerOptions<TWebSocket = typeof WebSocket.WebSocket> {
        // ... snip ...
        WebSocket?: TWebSocket | undefined;
    }
```

such that we could then do this in this package:

```
export interface WebsocketPluginOptions<TWebSocket = typeof WebSocket.WebSocket> {
  // ... snip ...
  options?: WebSocketServerOptions<TWebSocket>;
}
```

Without that underlying generic in the `WebSocketServerOptions` type I am not sure you can get TS to infer the right type for the implementation when registering the plugin.

The second problem is then making the `connection` passed into route handlers also generic over the same type, and passing that type around properly from the `.register` call to that callback. I am not sure that's possible right now without adding another generic type to the `FastifyServer` type which would happen in fastify core and is unlikely to be accepted since it's polluting core with types that'd only be used by some users.

What do you actually need the custom websocket type for, and could you use a module augmentation instead maybe?

**Comment by dsbudiac** [comment]
Yea, that seems like a pain.

I think I have a reasonable workaround. I'd decorate the server like so:

```ts
type WsHandler = (ws: MyWebSocket, req: FastifyRequest) => Promise<void>

declare module 'fastify' {
  interface FastifyInstance {
    ws: (url: string, handler: WsHandler) => Promise<void>
  }
}

server.decorate('ws', (url: string, handler: WsHandler) => {
  server.get(url, { websocket: true }, async (connection, req) => {
    return await handler(connection.socket as MyWebSocket, req)
  })
})
```

Then I can be all like:

```ts
server.ws('/my-route', async (ws, req) => {
  ws.foo()
})
```

I'm not sure I really need access to the underlying `SocketStream`. If I do, I could always just add it as an extra param on the `WsHandler`.

Haven't thought through all the use cases for a custom WebSocket class, but they discussed a few here: https://github.com/websockets/ws/pull/2007

A simple reason I'd extend it is to auto stringify object literals i.e.

```ts
class MyWebSocket extends WebSocket {
  send(input: any) {
    if (typeof input === 'string') return super.send(input)
    if (Buffer.isBuffer(input)) return super.send(input)
    const payload = JSON.stringify(input)
    super.send(payload)
  }
}
```

I'll submit my simple `ws` version bump fork as a pull request

**Comment by hotrungnhan** [comment]
is it work in current version ?

**Comment by Eomm** [comment]
Yes

**Comment by Eomm** [comment]
Why you asked then if you known the answer?

Anyway: If you install the package you get 8.5
https://github.com/fastify/fastify-websocket/pull/181#issuecomment-1064857913

This is a TS stuff that changes every 2 months and this issue is 1+ year old, so I would open a new issue with a code to replicate.

**Comment by hotrungnhan** [comment]
apologize for making you a little confused, I asked for a typed implementation.

> Why you asked then if you known the answer?
> 
> Anyway: If you install the package you get 8.5 [#181 (comment)](https://github.com/fastify/fastify-websocket/pull/181#issuecomment-1064857913)
> 
> This is a TS stuff that changes every 2 months and this issue is 1+ year old, so I would open a new issue with a code to replicate.
