### ISSUE TITLE
parametric routes broken

### ISSUE THREAD

**Issue by thar0x29a** [fastify/fastify-websocket#49]
Long story short: It looks to me like parametric routes did not got parsed anymore. 

fastify.get('/pools/:user', { websocket: true }, async (connection, req) => {
})

thats pretty odd

**Comment by mcollina** [comment]
would you like to send a PR to fix this?

**Comment by thomheymann** [comment]
Can you provide more details about your setup, code example and steps how to replicate this issue?

I am struggling to replicate this and there are units tests testing this functionality so it might be something to do with your code. 

Would also be good if you could share the error you're seeing or what the actual vs expected behaviour is.

**Comment by patarapolw** [comment]
It seems to be in the third parameter, according to `README.md`.

```js
fastify.get('/ws/:id', { websocket: true }, (connection, req, params) => {
  connection.write(`hi on stream ${params.id}`)
})
```
